[opener]
pdf = [
	{ run = 'zathura "$@"', desc = "zathura", block = false, for = "unix" },
]
edit = [
  { run = 'nvim "$@"', block = true },
]

[open]
pdf = [
  { mime = "application/pdf", use = [ "pdf", "reveal" ] },
]

[mgr]
keymap = [
  { on = [ "<C-n>" ], run = '''
      shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
  ''' },
]
